### ISSUE TITLE
Wrong extraction with some suffixes

### ISSUE THREAD

**Issue by hozez** [john-kurkowski/tldextract#116]
Extraction is wrong with the following domain suffixes:

- com.ru
- uk.com

**Repro:**
```
In [1]: tldextract.extract('www.marriott.com.ru')
Out[1]: ExtractResult(subdomain='www.marriott', domain='com', suffix='ru')
In [2]: tldextract.extract('www.parts.uk.com')
Out[2]: ExtractResult(subdomain='www.parts', domain='uk', suffix='com')
```
In both cases the first part of the suffix is mistakenly taken as the domain.

**Comment by john-kurkowski** [comment]
That uk.com is correct, as of writing, according to [this line](https://github.com/publicsuffix/list/blob/4dc16db295da02a51f67be88529ab4cdaa2945cb/public_suffix_list.dat#L10676) of the PSL. com.ru appears correct because that same file does not mention com.ru as a public suffix. If you think the former is incorrect or the latter should be a public suffix, you can [submit amendments to the PSL](https://publicsuffix.org/submit/).
