### ISSUE TITLE
Getting Error while installing on windows

### ISSUE THREAD

**Issue by salmanmohammad** [john-kurkowski/tldextract#120]
I am getting "error: package directory 'tldextract' does not exist" error when I am executing "setup.py build" command on windows 10.

Please help me out. How can I run the setup and program.

Thanks ad regards.

**Comment by john-kurkowski** [comment]
Can you give your exact repro steps? The exact commands you used to get to that error? What is the full output of all these steps?

**Comment by john-kurkowski** [comment]
Without knowing further, one of the first hits [Googling your error message](https://www.google.com/search?q=python+setup.py+"does+not+exist") is [this SO post](http://stackoverflow.com/questions/26148277/python-package-installation-issues). They say to make sure you're running the command within the source folder.

Additionally, rather than installing from source, you can run `pip install tldextract` from any location, per [the README](https://github.com/john-kurkowski/tldextract#installation).

**Comment by salmanmohammad** [comment]
Ok Thank you @john-kurkowski  for the help...:)

**Comment by john-kurkowski** [comment]
Did you figure it out? What solved your problem?

**Comment by salmanmohammad** [comment]
Sorry John I forget to reply you.
It get resolved , I forget what actually solved it. But it worked, I will
let you know once I get the steps.

Thanks and regards
Salman Mohammad
