### ISSUE TITLE
Unnecessarily costly import

### ISSUE THREAD

**Issue by huguesb** [john-kurkowski/tldextract#180]
The main `__init__.py` import the version from the `cli` module. The `cli` module has *expensive* import-time side effects, which leak into any import. The result is immediately visible on the following flame-graph gathered with py-spy:

<img width="1187" alt="Screen Shot 2019-12-04 at 3 10 55 PM" src="https://user-images.githubusercontent.com/7319881/70189609-98acce00-16a8-11ea-8e9f-9e5b7bbd6145.png">

This is a whopping 1.8s added to startup time!

This should be easy to fix by moving the version field to a separate file which is imported by both the `cli` and the main API, allowing the main API to stay clear of the `cli` module.

**Comment by john-kurkowski** [comment]
Your approach makes sense. Maybe even simpler: hardcode the version number in 2 places, `setup.py` and `__init__.py`? 

Am I reading that chart right, that it spends a lot of time in `pkg_resources`? I use that only to get the version number. Conventionally, `__version__` ought to appear in `__init__.py`. Externalizing the number would ultimately import `pkg_resources` anyway.

Its current location was an effort to DRY the version number, to define it exactly once in the project source. I'm overly sensitive to maintaining small bits of data like that, that easily get out of sync. But if importing `pkg_resources` (among others currently) is that expensive, I'm cool with remembering to update 2 numbers on release, instead of 1.

**Comment by lilydjwg** [comment]
Do you consider putting `__version__` in `__init__.py` and import it from `setup.py`? This will also remove the runtime dependency of setuptools.

**Comment by john-kurkowski** [comment]
Considering copying it to both files (DRY be damned). Thank you for the reminder about setuptools. The codebase evolved quite a bit since I jammed it in there, without understanding, in #57.
