### ISSUE TITLE
pypi lists 3.6 as supported

### ISSUE THREAD

**Issue by whiteowl3** [john-kurkowski/tldextract#242]
installing the current version from pip which lists support for 3.6 will fail on 3.6.

~~my project has a dependency on this and my 3.6 builds are failing with~~
```
    import tldextract

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/tldextract-3.1.2-py3.6.egg/tldextract/__init__.py:3: in <module>

    from .tldextract import extract, TLDExtract

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/tldextract-3.1.2-py3.6.egg/tldextract/tldextract.py:59: in <module>

    from .cache import DiskCache, get_cache_dir

../../../virtualenv/python3.6.7/lib/python3.6/site-packages/tldextract-3.1.2-py3.6.egg/tldextract/cache.py:11: in <module>

    from filelock import FileLock

E     File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/filelock-3.4.2-py3.6.egg/filelock/__init__.py", line 8

E       from __future__ import annotations

E                                        ^

E   SyntaxError: future feature annotations is not defined
```
filelock has dropped support for 3.6:
https://github.com/tox-dev/py-filelock/pull/125

**Comment by brycedrennan** [comment]
[According to Python](https://www.python.org/dev/peps/pep-0494/#lifespan): 
> As of 2021-12-23, 3.6 has reached the end-of-life phase of its release cycle 

I recommend updating to a newer version of python

**Comment by whiteowl3** [comment]
https://pypi.org/project/tldextract/

**Comment by john-kurkowski** [comment]
> filelock has dropped support for 3.6:
> [tox-dev/py-filelock#125](https://github.com/tox-dev/py-filelock/pull/125)

This is a py-filelock issue, not an issue caused by this repo. Which you noted, linking to the py-filelock issue, and it's in the final line of the stack trace. You can work around this by installing an earlier version of py-filelock.

Yeah, breaking changes on a patch release are upsetting. That's a "too hot" debate too. 😄 See https://github.com/tox-dev/py-filelock/issues/126.

**Comment by john-kurkowski** [comment]
> breaking changes on a patch release are upsetting … tox-dev/py-filelock#126.

To be fair to their project, any issue should be rare. That discussion notes that pip 9 and newer honor `python_requires`, and so those pip versions won't attempt to install the py-filelock version that declares that it drops Python 3.6 support. That's why CI is still passing on this project. @whiteowl3, maybe you're using a very old pip?
