### ISSUE TITLE
resurrect need to pass custom requests session (old #158, etc)

### ISSUE THREAD

**Issue by mcooperman** [john-kurkowski/tldextract#250]
As best i can tell, this is not implemented. Sorry if i missed something, just squash it then...
needed to go through a proxy.
my thoughts are
- allow a custom session to be passed by code
- or pick up http_proxy, https_proxy, no_proxy from environment if present
- or override from command line
working on my own patch and happy to merge it in if wanted ;)

**Comment by mcooperman** [comment]
it looks like default session behavior _may_ pickup some environment settings, assuming one likes the default behavior.
However, verify/don't verify SSL Certificates doesn't seem to be covered - and is an issue in some environments (proxies).
this can be set at the session level.
also, control of the trust_env setting on the session affects what environment variables are incorporated, and this can be set at the session level.

**Comment by john-kurkowski** [comment]
> allow a custom session to be passed by code

I lean toward this option. It leverages Requests' existing interface. I lean away from additional, idiosyncratic globals, because globals. I lean away from more CLI, because it's a niche use case and this project isn't primarily a CLI.

The custom session option is roughly described in #158. Can we close this as duplicate, and concentrate further discussion there?

**Comment by mcooperman** [comment]
surely. i'll go along. reading up on contributions, etc. i think i have something working. trying to make sure tested thoroughly.

**Comment by john-kurkowski** [comment]
Cool. Closing as dupe. Tracked in #158.
