### ISSUE TITLE
domain and public suffix urls

### ISSUE THREAD

**Issue by trbateman** [john-kurkowski/tldextract#56]
Websites such as: 
- http://www.gov.uk 
- http://www.nhs.uk
are urls which are both public suffixes and domains. E.g.

http://www.tfl.gov.uk
http://www.nhsdirect.nhs.uk 

This leads to them being separated incorrectly in some circumstances.

**Comment by xdanx** [comment]
Hello,

Since June last year I think gov.uk should be a valid domain, since now everybody is allowed to register a .uk domain: <http://en.wikipedia.org/wiki/.uk>
`New registrations directly under .uk have been accepted by Nominet since 10 June 2014 08:00 BST, however there is a reservation period for existing customers who already have a .co.uk, .org.uk, .me.uk, .net.uk, .ltd.uk or .plc.uk domain to claim the corresponding .uk domain, which runs until 07:59 BST on 10 June 2019`

But I agree with @john-kurkowski, the exception should be added in the PSL. In this case I think the domain should be 'gov' and suffix 'uk'

**Comment by john-kurkowski** [comment]
Closing in favor of someone [submitting the exception to the PSL](https://publicsuffix.org/submit/).
