### ISSUE TITLE
ImportError: No module named 'requests_file'

### ISSUE THREAD

**Issue by pantuts** [john-kurkowski/tldextract#99]
OS: Manjaro
Python: 3.5

Tried to import it but having this error 'requests_file'.

![selection_016](https://cloud.githubusercontent.com/assets/894185/14812811/69ef6900-0bd1-11e6-8aca-e589fab44e62.png)

**Comment by john-kurkowski** [comment]
Hmm, I can't reproduce from a clean virtualenv:

```zsh
pyenv virtualenv 3.5.0 99test
pyenv local 99test
pip install tldextract
python -c 'import tldextract'
```

You're using `pip install tldextract` to install, from the README? Were there errors during install?

**Comment by pantuts** [comment]
yep from pip and no errors.. actually pip3.. since there is pip2 intended for python2.7 packages..

**Comment by syphar** [comment]
@pantuts 
this error happened to us too

reason is that `tldextract` has a new requirement `requests-file` (see [`setup.py`](https://github.com/john-kurkowski/tldextract/blob/ff7f4bedfb364b460a162d5b7d799890fad57b01/setup.py#L34))

we're using `pip-sync` to cleanup the virtualenv following the `requirements.txt` file. So the new `requests-file` requirement gets installed when upgrading the `tldextract` package, and then removed again by `pip-sync` because it's not in the `reuirements.txt` file.

**Comment by pantuts** [comment]
yup correct. i did `sudo pip3 install requests-file` and import now works.

**Comment by john-kurkowski** [comment]
Help me understand. This issue only affects those using `pip-sync`? `pip-sync` users have to remember to manually add requirements, every time a dependency adds a requirement? There's nothing further this library can do?
